import dims from '@/lib/image-dimensions.json';
import { BASE_PATH } from '@/lib/asset';

const MAP = dims as unknown as Record<string, [number, number]>;

/**
 * Intrinsic [width, height] of a public/ image, from lib/image-dimensions.json
 * (generated by scripts/gen-image-dims.mjs). Accepts plain paths, asset()
 * paths with the base path, URL-encoded paths and paths with a query string.
 * Returns undefined for anything else (external URLs, unknown files).
 */
export function lookupImageSize(src: unknown): [number, number] | undefined {
  if (typeof src !== 'string' || !src.startsWith('/') || src.startsWith('//')) return undefined;
  let p = src.split(/[?#]/)[0];
  if (BASE_PATH && p.startsWith(BASE_PATH + '/')) p = p.slice(BASE_PATH.length);
  if (MAP[p]) return MAP[p];
  try {
    return MAP[decodeURI(p)];
  } catch {
    return undefined;
  }
}
